[build]
target = "index.html"
release = false
dist = "dist"
public_url = "/static/"

[watch]
ignore = ["dist"]

[serve]
address = "0.0.0.0"
port = 3000
open = false

[[proxy]]
rewrite = "/mcp.orchestrator.v1.McpOrchestratorService/"
backend = "http://localhost:3000/mcp.orchestrator.v1.McpOrchestratorService/"
